String.toLocaleString({

	"es": {
    "%game-intro"           : "Join the <strong>Mayas!</strong>",
    "%restart-button"       : "Play Again",
    "%keep-playing-button"  : "Keep going",
    "%retry-button"         : "Retry",
    "%game-won"             : "You win!",
    "%game-over"            : "Game over!",
    "%game-explanation"     : "<strong class=\"important\">How to play:</strong> Use your <strong>arrow keys</strong> to move the tiles. When two tiles with the same symbol touch, they <strong>get promoted!</strong>",
    "%disclaimer"           : "<strong class=\"important\">Note:</strong> This site is a spin-off of the official version of <a href=\"http://git.io/2048\">2048</a> created by <a href=\"http://gabrielecirulli.com\" target=\"_blank\">Gabriele Cirulli</a>.",
    "%credits"              : "Mayan images by <a href=\"http://www.georgetowncupcake.com/\" title=\"Georgetown Cupcake | DC Cupcakes | About\">Georgetown Cupcake</a>.",
    "%tweet1"               : "I scored \"",
    "%tweet2"               : " at 2048-MAYAS #2048game",
    "%tile-legend"          : "<strong class=\"important\">Tile Legend:</strong>",
    '%2'                    : 'one',
    '%4'                    : 'two',
    '%8'                    : 'three',
    '%16'                   : 'four',
    '%32'                   : 'five',
    '%64'                   : 'six',
    '%128'                  : 'seven',
    '%256'                  : 'eight',
    '%512'                  : 'nine',
    '%1024'                 : 'ten',
    '%2048'                 : 'eleven',
    '%4096'                 : 'twelve',
    '%8192'                 : 'thirteen',
    '%p0'                   : 'one',
    '%p4'                   : 'two', 
    '%p8'                   : 'three', 
    '%p16'                  : 'four', 
    '%p32'                  : 'five', 
    '%p64'                  : 'six', 
    '%p128'                 : 'seven', 
    '%p256'                 : 'eight', 
    '%p512'                 : 'nine', 
    '%p1024'                : 'ten', 
    '%p2048'                : 'eleven', 
    '%p4096'                : 'twelve', 
    '%p8192'                : 'thirteen', 
  }   ,

  "en": {
    "%game-intro"           : "Join the <strong>Mayas!</strong>",
    "%restart-button"       : "Play Again",
    "%keep-playing-button"  : "Keep going",
    "%retry-button"         : "Retry",
    "%game-won"             : "You win!",
    "%game-over"            : "Game over!",
    "%game-explanation"     : "<strong class=\"important\">How to play:</strong> Use your <strong>arrow keys</strong> to move the tiles. When two tiles with the same symbol touch, they <strong>get promoted!</strong>",
    "%disclaimer"           : "<strong class=\"important\">Note:</strong> This site is a spin-off of the official version of <a href=\"http://git.io/2048\">2048</a> created by <a href=\"http://gabrielecirulli.com\" target=\"_blank\">Gabriele Cirulli</a>.",
    "%credits"              : "Mayan images by <a href=\"http://www.georgetowncupcake.com/\" title=\"Georgetown Cupcake | DC Cupcakes | About\">Georgetown Cupcake</a>.",
    "%tweet1"               : "I scored \"",
    "%tweet2"               : " at 2048-MAYAS #2048game",
    "%tile-legend"          : "<strong class=\"important\">Tile Legend:</strong>",
    '%2'                    : 'one',
    '%4'                    : 'two',
    '%8'                    : 'three',
    '%16'                   : 'four',
    '%32'                   : 'five',
    '%64'                   : 'six',
    '%128'                  : 'seven',
    '%256'                  : 'eight',
    '%512'                  : 'nine',
    '%1024'                 : 'ten',
    '%2048'                 : 'eleven',
    '%4096'                 : 'twelve',
    '%8192'                 : 'thirteen',
    '%p0'                   : 'one',
    '%p4'                   : 'two', 
    '%p8'                   : 'three', 
    '%p16'                  : 'four', 
    '%p32'                  : 'five', 
    '%p64'                  : 'six', 
    '%p128'                 : 'seven', 
    '%p256'                 : 'eight', 
    '%p512'                 : 'nine', 
    '%p1024'                : 'ten', 
    '%p2048'                : 'eleven', 
    '%p4096'                : 'twelve', 
    '%p8192'                : 'thirteen', 
  }                            

});
